# Generated by Django 3.0.5 on 2020-04-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('developer', models.CharField(max_length=50)),
                ('publisher', models.CharField(default='Nintendo', max_length=50)),
                ('platform', models.CharField(max_length=50)),
                ('release_year', models.IntegerField()),
            ],
        ),
    ]
