# Generated by Django 3.0.5 on 2020-04-13 15:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('developer', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=100)),
                ('release_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('developer', models.CharField(max_length=20)),
                ('generation', models.IntegerField(default=1)),
                ('release_year', models.IntegerField(default=1980)),
            ],
        ),
        migrations.CreateModel(
            name='PlayTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('hours_played', models.IntegerField(default=0)),
                ('completed', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default=('N', 'No'), max_length=1)),
                ('games', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Games')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='games',
            name='platform',
            field=models.ManyToManyField(to='main_app.Platform'),
        ),
    ]
