# Generated by Django 3.0.5 on 2020-04-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('developer', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('completed', models.BooleanField(default=False)),
                ('hours_played', models.IntegerField(default=0)),
                ('playable_on', models.CharField(max_length=20)),
                ('genre', models.CharField(max_length=100)),
                ('release_year', models.IntegerField()),
            ],
        ),
    ]
