# Generated by Django 3.0.5 on 2020-04-16 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='user',
        ),
    ]
