# Generated by Django 3.0.5 on 2020-04-12 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_games_playable_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='game',
        ),
        migrations.AddField(
            model_name='games',
            name='platform',
            field=models.ManyToManyField(to='main_app.Platform'),
        ),
    ]
