# Generated by Django 3.0.5 on 2020-04-12 20:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200412_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='games',
            name='hours_played',
        ),
        migrations.RemoveField(
            model_name='games',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='developer',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='generation',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='name',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='release_year',
        ),
        migrations.CreateModel(
            name='PlayTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2020, 4, 12))),
                ('hours_played', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Games')),
            ],
        ),
    ]
