# Generated by Django 3.0.5 on 2020-04-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200412_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playtime',
            name='completed',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='No', max_length=1),
        ),
    ]
