# Generated by Django 3.0.5 on 2020-04-12 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200412_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playtime',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
