# Generated by Django 3.0.5 on 2020-04-12 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20200412_2044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playtime',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='playtime',
            old_name='game',
            new_name='games',
        ),
    ]
